version: "3.7"
services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    volumes:
      - /frontend/node_modules
      - ./:/frontend
    ports:
      - "3000:3000"
    stdin_open: true